apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: keycloak
spec:
  lookupPolicy:
    local: false
  tags:
    - name: latest
      from:
        kind: DockerImage
        name: registry.redhat.io/rh-sso-7/sso74-openshift-rhel8